name: NPM Publish
on: [push]

jobs:
  node-linux:
    name: vectordb (${{ matrix.config.arch}}-unknown-linux-musl)
    runs-on: ${{ matrix.config.runner }}
    container: ${{ matrix.config.container }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: x86_64
            runner: ubuntu-2404-4x-arm64
            container: alpine:edge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true